devscoop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from news.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("news/", include("news.urls")),
    path("api/v1/news/", include("news.urls")),
    path("admin/", admin.site.urls),
    path("user/", include("feeduser.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(
    #     settings.VUE_IMG_URL, document_root=settings.VUE_IMG_ROOT
    # )

news/urls.py
from django.urls import path

from news.views import (
    LatestNewsItemListView,
    NewsItemApiListCreateView,
    NewsItemDetailView,
    NewsItemObjectApiUpdateDeleteView,
)

app_name = "news"
urlpatterns = [
    path("latest", LatestNewsItemListView.as_view(), name="latest"),
    path("detail/<str:pk>", NewsItemDetailView.as_view(), name="detail"),
    # api urls
    path("item/all/", NewsItemApiListCreateView.as_view(), name="all-items"),
    path(
        "item/<str:pk>",
        NewsItemObjectApiUpdateDeleteView.as_view(),
        name="api-object-modify",
    ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block page_title %}{% endblock %} | Dev Scoop</title>
</head>
<body class="bg-secondary bg-opacity-10">
  <nav class="navbar navbar-dark navbar-expand-lg bg-dark fixed-top border-bottom border-secondary p-1">
    <div class="container-fluid mx-3">
      <a class="navbar-brand" href="/">
          DevScoop
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
          data-bs-target="#navmenu">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navmenu">
          <ul class="navbar-nav">
              <li class="nav-item">
                <a class="navbar-brand" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="navbar-brand" href="{% url 'news:latest' %}">Latest</a>
              </li>
              <li class="nav-item">
                <a class="navbar-brand" href="{% url 'news:latest' %}?item_type=story">Stories</a>
              </li>
              <li class="nav-item">
                <a class="navbar-brand" href="{% url 'news:latest' %}?item_type=job">Jobs</a>
              </li>
              <li class="nav-item">
                <a class="navbar-brand" href="{% url 'news:latest' %}?item_type=poll">Polls</a>
              </li>
          </ul>
      </div>
    </div> 
  </nav>
    <div class="mt-5 text-black" style="padding-top: 20px;">
      {% block content %}{% endblock %}
    </div>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static  %}
{% block page_title %}Home{% endblock %}
{% block content %}
<div class="p-5 rounded-3 mb-5">
    <div class="row">
        <div class="col-xs-12 col-sm-6 d-sm-flex">
            <img src="{% static 'img/hero.svg' %}" alt="hero image" class="img-fluid">
        </div>
        <div class="col-xs-12 col-sm-6 d-flex align-items-center">
            <div class="row">
                <h1>Welcome to the Dev Scoop</h1>
                <p class="lead">
                    The latest updates in the dev community.
                </p>
                <a href="{% url 'news:latest' %}" class="btn btn-primary text-white col-md-4 ms-3"><span class="me-1">Latest News</span></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}